# CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: realsalmon/alpinelinux-python-boto3:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: make tests-actual
workflows:
  version: 2
  build:
    jobs:
      - test
